import Head from "next/head";
import About from "../components/Home/About";
import Intro from "../components/Home/Intro";
import Location from "../components/Home/Location";
import Services from "../components/Home/Services";

export default function Home() {
  return (
    <div className="relative">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Intro />
      <About />
      <Services />
      <Location />
    </div>
  );
}
